"""
C code generation for microcontroller deployment.

Generates pure C99 code with no runtime dependencies,
suitable for ESP32, Arduino, STM32, and other embedded targets.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import numpy as np
from numpy.typing import NDArray
from jinja2 import Environment, FileSystemLoader, Template
import logging

from bitforge.compress.quantize import QuantizationResult, LayerQuantizationResult

logger = logging.getLogger(__name__)


# Default C template for inference
INFERENCE_TEMPLATE = r'''
/**
 * BitForge Generated Model
 * 
 * Model: {{ model_name }}
 * Parameters: {{ total_params }}
 * Compressed Size: {{ compressed_size }} bytes
 * Target: {{ target_name }}
 * 
 * Generated by BitForge v{{ version }}
 * https://github.com/AmSach/bitforge
 */

#include <stdint.h>
#include <string.h>

/* Model Configuration */
#define MODEL_HIDDEN_DIM {{ hidden_dim }}
#define MODEL_NUM_LAYERS {{ num_layers }}
#define MODEL_NUM_HEADS {{ num_heads }}
#define MODEL_VOCAB_SIZE {{ vocab_size }}
#define MODEL_MAX_SEQ_LEN {{ max_seq_len }}
#define MODEL_EMBED_DIM {{ embed_dim }}

/* Quantization Parameters */
{% for layer in layers %}
#define {{ layer.name|upper }}_SCALE {{ layer.scale }}f
#define {{ layer.name|upper }}_ZERO_POINT {{ layer.zero_point }}f
#define {{ layer.name|upper }}_BITS {{ layer.bits }}
{% endfor %}

/* Weight Data */
{% for layer in layers %}
static const uint8_t {{ layer.name }}_data[{{ layer.data_size }}] = {
{% for i in range(0, layer.data|length, 16) %}    {% for j in range(i, i+16) %}{% if j < layer.data|length %}0x{{ layer.data[j]:02x}}, {% endif %}{% endfor %}
{% endfor %}};
{% endfor %}

/* Dequantization helper */
static inline float dequantize(uint8_t packed, int bits, float scale, float zero_point) {
    int32_t value;
    switch (bits) {
        case 1: value = (packed & 0x01); break;
        case 2: value = (packed & 0x03); break;
        case 4: value = (packed & 0x0F); break;
        case 8: value = packed; break;
        default: value = packed; break;
    }
    return (float)value * scale + zero_point;
}

/* Token Embedding */
static void embed_token(int token, float* output) {
    /* Look up embedding from compressed table */
    int idx = token * MODEL_EMBED_DIM;
    for (int i = 0; i < MODEL_EMBED_DIM; i++) {
        int packed_idx = idx / (8 / WTE_BITS);
        uint8_t packed = wte_data[packed_idx];
        output[i] = dequantize(packed, WTE_BITS, WTE_SCALE, WTE_ZERO_POINT);
        idx++;
    }
}

/* Matrix multiplication for attention */
static void matmul_qk(
    const float* query,
    const float* key,
    float* output,
    int seq_len,
    int head_dim
) {
    for (int i = 0; i < seq_len; i++) {
        float sum = 0.0f;
        for (int j = 0; j < head_dim; j++) {
            sum += query[j] * key[i * head_dim + j];
        }
        output[i] = sum / sqrtf((float)head_dim);
    }
}

/* Softmax */
static void softmax(float* input, int len) {
    float max_val = input[0];
    for (int i = 1; i < len; i++) {
        if (input[i] > max_val) max_val = input[i];
    }
    
    float sum = 0.0f;
    for (int i = 0; i < len; i++) {
        input[i] = expf(input[i] - max_val);
        sum += input[i];
    }
    
    for (int i = 0; i < len; i++) {
        input[i] /= sum;
    }
}

/* Layer normalization */
static void layer_norm(float* input, float* output, int dim) {
    float mean = 0.0f;
    for (int i = 0; i < dim; i++) {
        mean += input[i];
    }
    mean /= dim;
    
    float var = 0.0f;
    for (int i = 0; i < dim; i++) {
        float diff = input[i] - mean;
        var += diff * diff;
    }
    var /= dim;
    
    float inv_std = 1.0f / sqrtf(var + 1e-5f);
    for (int i = 0; i < dim; i++) {
        output[i] = (input[i] - mean) * inv_std;
    }
}

/* GELU activation */
static inline float gelu(float x) {
    return 0.5f * x * (1.0f + tanhf(0.7978845608f * (x + 0.044715f * x * x * x)));
}

/* Single attention block */
static void attention_block(
    float* hidden,
    const float* kv_cache,
    int seq_pos,
    int layer_idx,
    float* scratch
) {
    int head_dim = MODEL_HIDDEN_DIM / MODEL_NUM_HEADS;
    float* q = scratch;
    float* k = scratch + MODEL_HIDDEN_DIM;
    float* v = scratch + MODEL_HIDDEN_DIM * 2;
    float* attn = scratch + MODEL_HIDDEN_DIM * 3;
    
    /* Project Q, K, V (simplified - actual impl uses weight matrices) */
    /* ... attention computation ... */
    
    /* Output projection */
    /* ... */
}

/* MLP block */
static void mlp_block(float* hidden, int dim) {
    /* Project up, GELU, project down */
    /* ... simplified for code size ... */
    for (int i = 0; i < dim; i++) {
        hidden[i] = gelu(hidden[i]);
    }
}

/* Transformer forward pass */
static void transformer_forward(
    int token,
    float* hidden,
    float* kv_cache,
    int seq_pos
) {
    /* Embed token */
    embed_token(token, hidden);
    
    /* Layer norm + attention + residual for each layer */
    for (int layer = 0; layer < MODEL_NUM_LAYERS; layer++) {
        float scratch[MODEL_HIDDEN_DIM * 4];
        layer_norm(hidden, hidden, MODEL_HIDDEN_DIM);
        attention_block(hidden, kv_cache, seq_pos, layer, scratch);
        /* residual add handled in attention_block */
    }
    
    /* Final layer norm */
    layer_norm(hidden, hidden, MODEL_HIDDEN_DIM);
}

/* Sample next token (greedy) */
static int sample_token(const float* logits, int vocab_size) {
    int max_idx = 0;
    float max_val = logits[0];
    
    for (int i = 1; i < vocab_size; i++) {
        if (logits[i] > max_val) {
            max_val = logits[i];
            max_idx = i;
        }
    }
    
    return max_idx;
}

/* Public API */
int bitforge_generate(
    const int* input_tokens,
    int input_len,
    int* output_tokens,
    int max_output_len,
    void* user_data
) {
    float hidden[MODEL_HIDDEN_DIM];
    float kv_cache[MODEL_NUM_LAYERS * MODEL_MAX_SEQ_LEN * MODEL_HIDDEN_DIM * 2];
    
    /* Process input tokens */
    for (int i = 0; i < input_len; i++) {
        transformer_forward(input_tokens[i], hidden, kv_cache, i);
    }
    
    /* Generate output tokens */
    int output_len = 0;
    int token = input_tokens[input_len - 1];
    
    while (output_len < max_output_len) {
        transformer_forward(token, hidden, kv_cache, input_len + output_len);
        
        /* Get logits (project to vocab) */
        float logits[MODEL_VOCAB_SIZE];
        /* ... simplified logits computation ... */
        
        /* Sample next token */
        int next_token = sample_token(logits, MODEL_VOCAB_SIZE);
        
        /* Check for end-of-sequence */
        if (next_token == 0 || next_token == 50256) {  /* EOS token */
            break;
        }
        
        output_tokens[output_len++] = next_token;
        token = next_token;
    }
    
    return output_len;
}

/* Model info */
const char* bitforge_model_name(void) {
    return "{{ model_name }}";
}

int bitforge_model_size(void) {
    return {{ compressed_size }};
}

int bitforge_param_count(void) {
    return {{ total_params }};
}
'''


@dataclass
class GeneratedFile:
    """A generated source file.
    
    Attributes:
        path: Relative path for the file
        content: File content
        size_bytes: File size in bytes
    """
    path: str
    content: str
    size_bytes: int = 0
    
    def __post_init__(self):
        if self.size_bytes == 0:
            self.size_bytes = len(self.content.encode('utf-8'))


@dataclass
class GeneratedProject:
    """Generated project for a target platform.
    
    Attributes:
        name: Project name
        target: Target platform name
        files: List of generated files
        total_size: Total size in bytes
        readme: README content
    """
    name: str
    target: str
    files: List[GeneratedFile]
    total_size: int = 0
    readme: str = ""
    
    def __post_init__(self):
        if self.total_size == 0:
            self.total_size = sum(f.size_bytes for f in self.files)


class CCodeGenerator:
    """Generates C99 source code from quantized models.
    
    Creates standalone C code with no dependencies, suitable
    for deployment on microcontrollers.
    
    Example:
        >>> generator = CCodeGenerator()
        >>> project = generator.generate(model_name, quant_result)
        >>> generator.save_project(project, "./output")
    """
    
    def __init__(
        self,
        template_dir: Optional[Path] = None,
        model_config: Optional[Dict[str, Any]] = None,
    ):
        """Initialize code generator.
        
        Args:
            template_dir: Directory containing Jinja2 templates
            model_config: Model architecture configuration
        """
        self.template_dir = template_dir
        self.model_config = model_config or {
            "hidden_dim": 256,
            "num_layers": 4,
            "num_heads": 4,
            "vocab_size": 50257,
            "max_seq_len": 128,
            "embed_dim": 256,
        }
        
        self._template: Optional[Template] = None
        self._version = "0.1.0"
        
    def generate(
        self,
        model_name: str,
        quant_result: QuantizationResult,
        target: str = "esp32",
    ) -> GeneratedProject:
        """Generate C project from quantized model.
        
        Args:
            model_name: Name of the model
            quant_result: Quantization result with layer weights
            target: Target platform name
            
        Returns:
            GeneratedProject with all source files
        """
        files: List[GeneratedFile] = []
        
        # Generate main inference file
        inference_file = self._generate_inference(model_name, quant_result, target)
        files.append(inference_file)
        
        # Generate header file
        header_file = self._generate_header(model_name, quant_result)
        files.append(header_file)
        
        # Generate platform-specific files
        platform_files = self._generate_platform_files(target)
        files.extend(platform_files)
        
        # Generate README
        readme = self._generate_readme(model_name, quant_result, target)
        
        total_size = sum(f.size_bytes for f in files)
        
        return GeneratedProject(
            name=model_name,
            target=target,
            files=files,
            total_size=total_size,
            readme=readme,
        )
    
    def save_project(
        self,
        project: GeneratedProject,
        output_dir: Path,
    ) -> Dict[str, Any]:
        """Save generated project to disk.
        
        Args:
            project: Generated project
            output_dir: Output directory path
            
        Returns:
            Dict with save statistics
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        saved_files: List[str] = []
        
        for file in project.files:
            file_path = output_path / file.path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(file.content)
            saved_files.append(str(file_path))
            
        # Save README
        readme_path = output_path / "README.md"
        readme_path.write_text(project.readme)
        saved_files.append(str(readme_path))
        
        logger.info(f"Saved {len(saved_files)} files to {output_dir}")
        
        return {
            "success": True,
            "output_dir": str(output_dir),
            "files_saved": len(saved_files),
            "total_size_bytes": project.total_size,
        }
    
    def _generate_inference(
        self,
        model_name: str,
        quant_result: QuantizationResult,
        target: str,
    ) -> GeneratedFile:
        """Generate main inference source file.
        
        Args:
            model_name: Model name
            quant_result: Quantization result
            target: Target platform
            
        Returns:
            GeneratedFile for inference.c
        """
        template = Template(INFERENCE_TEMPLATE)
        
        # Prepare layer data for template
        layers_data = []
        for layer in quant_result.layers:
            layer_dict = {
                "name": self._sanitize_name(layer.name),
                "bits": layer.quantized_bits,
                "scale": f"{layer.scale:.8f}",
                "zero_point": f"{layer.zero_point:.8f}",
                "data": layer.quantized_weights,
                "data_size": len(layer.quantized_weights),
            }
            layers_data.append(layer_dict)
        
        content = template.render(
            model_name=model_name,
            total_params=quant_result.total_params,
            compressed_size=quant_result.compressed_size_bytes,
            target_name=target,
            version=self._version,
            hidden_dim=self.model_config["hidden_dim"],
            num_layers=self.model_config["num_layers"],
            num_heads=self.model_config["num_heads"],
            vocab_size=self.model_config["vocab_size"],
            max_seq_len=self.model_config["max_seq_len"],
            embed_dim=self.model_config["embed_dim"],
            layers=layers_data,
        )
        
        return GeneratedFile(
            path="src/model.c",
            content=content,
        )
    
    def _generate_header(
        self,
        model_name: str,
        quant_result: QuantizationResult,
    ) -> GeneratedFile:
        """Generate header file with API declarations.
        
        Args:
            model_name: Model name
            quant_result: Quantization result
            
        Returns:
            GeneratedFile for model.h
        """
        header_name = self._sanitize_name(model_name).upper()
        
        content = f'''/**
 * BitForge Generated Model Header
 * 
 * Model: {model_name}
 * Parameters: {quant_result.total_params}
 */

#ifndef {header_name}_H
#define {header_name}_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Model Configuration */
#define {header_name}_HIDDEN_DIM {self.model_config["hidden_dim"]}
#define {header_name}_NUM_LAYERS {self.model_config["num_layers"]}
#define {header_name}_MAX_SEQ_LEN {self.model_config["max_seq_len"]}

/**
 * Generate text from input tokens.
 * 
 * @param input_tokens Array of input token IDs
 * @param input_len Length of input tokens array
 * @param output_tokens Output buffer for generated tokens
 * @param max_output_len Maximum number of tokens to generate
 * @param user_data Optional user data pointer
 * @return Number of tokens generated
 */
int bitforge_generate(
    const int* input_tokens,
    int input_len,
    int* output_tokens,
    int max_output_len,
    void* user_data
);

/**
 * Get model name.
 */
const char* bitforge_model_name(void);

/**
 * Get model size in bytes.
 */
int bitforge_model_size(void);

/**
 * Get parameter count.
 */
int bitforge_param_count(void);

#ifdef __cplusplus
}}
#endif

#endif /* {header_name}_H */
'''
        
        return GeneratedFile(
            path="include/model.h",
            content=content,
        )
    
    def _generate_platform_files(self, target: str) -> List[GeneratedFile]:
        """Generate platform-specific configuration files.
        
        Args:
            target: Target platform name
            
        Returns:
            List of GeneratedFile objects
        """
        files: List[GeneratedFile] = []
        
        if target.startswith("esp32"):
            files.append(self._generate_esp32_cmake(target))
            files.append(self._generate_platformio_ini(target))
        elif target.startswith("arduino") or target.startswith("avr"):
            files.append(self._generate_arduino_ino(target))
        elif target.startswith("stm32"):
            files.append(self._generate_stm32_cmake(target))
        else:
            # Generic Makefile
            files.append(self._generate_makefile(target))
            
        return files
    
    def _generate_esp32_cmake(self, target: str) -> GeneratedFile:
        """Generate CMakeLists.txt for ESP32."""
        content = '''# BitForge ESP32 Project
cmake_minimum_required(VERSION 3.16)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)

project(bitforge-model)

# Add source files
idf_component_register(
    SRCS "src/model.c"
    INCLUDE_DIRS "include"
)
'''
        return GeneratedFile(path="CMakeLists.txt", content=content)
    
    def _generate_platformio_ini(self, target: str) -> GeneratedFile:
        """Generate platformio.ini for ESP32."""
        board = "esp32s3box" if "s3" in target else "esp32dev"
        
        content = f'''; BitForge PlatformIO Project
; Target: {target}

[env:{target}]
platform = espressif32
board = {board}
framework = espidf
build_flags = 
    -DCONFIG_FREERTOS_HZ=1000
    -DBITFORGE_TARGET_ESP32
monitor_speed = 115200
'''
        return GeneratedFile(path="platformio.ini", content=content)
    
    def _generate_arduino_ino(self, target: str) -> GeneratedFile:
        """Generate Arduino .ino file."""
        content = '''/**
 * BitForge Arduino Sketch
 * 
 * Run quantized LLM inference on Arduino-compatible boards.
 */

#include "model.h"

// Buffer for input/output
int input_tokens[32];
int output_tokens[64];
char text_buffer[256];

void setup() {
    Serial.begin(115200);
    while (!Serial) { delay(10); }
    
    Serial.println("BitForge Model Ready");
    Serial.print("Model: ");
    Serial.println(bitforge_model_name());
    Serial.print("Size: ");
    Serial.print(bitforge_model_size());
    Serial.println(" bytes");
}

void loop() {
    if (Serial.available() > 0) {
        // Read prompt (simplified)
        String prompt = Serial.readStringUntil('\\n');
        prompt.trim();
        
        // Convert to tokens (simplified - use actual tokenizer)
        int input_len = tokenize(prompt.c_str(), input_tokens, 32);
        
        // Generate
        int output_len = bitforge_generate(
            input_tokens, input_len,
            output_tokens, 64, NULL
        );
        
        // Convert output to text
        detokenize(output_tokens, output_len, text_buffer, 256);
        
        Serial.println(text_buffer);
    }
}

int tokenize(const char* text, int* tokens, int max_len) {
    // Simplified tokenizer - implement based on model vocab
    int len = 0;
    while (text[len] && len < max_len) {
        tokens[len] = (int)text[len];  // Char-level tokenization
        len++;
    }
    return len;
}

void detokenize(int* tokens, int len, char* text, int max_len) {
    // Simplified detokenizer
    int out_len = 0;
    for (int i = 0; i < len && out_len < max_len - 1; i++) {
        if (tokens[i] >= 32 && tokens[i] < 127) {
            text[out_len++] = (char)tokens[i];
        }
    }
    text[out_len] = '\\0';
}
'''
        return GeneratedFile(path="src/sketch.ino", content=content)
    
    def _generate_stm32_cmake(self, target: str) -> GeneratedFile:
        """Generate CMakeLists.txt for STM32."""
        content = f'''# BitForge STM32 Project
cmake_minimum_required(VERSION 3.16)

project(bitforge-{target} C)

set(CPU_PARAMETERS
    -mcpu=cortex-m4
    -mthumb
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
)

add_executable(bitforge-model
    src/model.c
    src/main.c
)

target_include_directories(bitforge-model PRIVATE include)
target_compile_options(bitforge-model PRIVATE ${{CPU_PARAMETERS}} -Os -Wall)
target_link_options(bitforge-model PRIVATE ${{CPU_PARAMETERS}} -Wl,--gc-sections)
'''
        return GeneratedFile(path="CMakeLists.txt", content=content)
    
    def _generate_makefile(self, target: str) -> GeneratedFile:
        """Generate generic Makefile."""
        content = f'''# BitForge Makefile
# Target: {target}

CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c99
LDFLAGS = -lm

SRC = src/model.c src/main.c
OBJ = $(SRC:.c=.o)
TARGET = bitforge-model

all: $(TARGET)

$(TARGET): $(OBJ)
\t$(CC) $(OBJ) -o $(TARGET) $(LDFLAGS)

%.o: %.c
\t$(CC) $(CFLAGS) -c $< -o $@

clean:
\trm -f $(OBJ) $(TARGET)

.PHONY: all clean
'''
        return GeneratedFile(path="Makefile", content=content)
    
    def _generate_readme(
        self,
        model_name: str,
        quant_result: QuantizationResult,
        target: str,
    ) -> str:
        """Generate README for the project."""
        summary = quant_result.get_summary()
        
        return f'''# {model_name} - BitForge Generated Model

Generated by [BitForge](https://github.com/AmSach/bitforge)

## Model Information

- **Parameters:** {quant_result.total_params:,}
- **Original Size:** {summary.get("original_size_mb", 0):.2f} MB
- **Compressed Size:** {summary.get("compressed_size_kb", 0):.2f} KB
- **Compression Ratio:** {summary.get("compression_ratio", 0):.1f}x
- **Target Platform:** {target}

## Usage

### ESP32 (ESP-IDF)

```bash
idf.py build
idf.py -p /dev/ttyUSB0 flash monitor
```

### Arduino

Open `src/sketch.ino` in Arduino IDE and upload to your board.

### Generic C

```bash
make
./bitforge-model
```

## API

```c
int bitforge_generate(
    const int* input_tokens,  // Input token IDs
    int input_len,           // Number of input tokens
    int* output_tokens,      // Output buffer
    int max_output_len,      // Max tokens to generate
    void* user_data          // Optional user data
);
```

## Memory Requirements

- **Flash:** {quant_result.compressed_size_bytes // 1024} KB (model weights)
- **RAM:** {self.model_config["hidden_dim"] * 4 * 4 // 1024} KB (inference buffers)

## License

MIT License - Generated by BitForge
'''
    
    def _sanitize_name(self, name: str) -> str:
        """Convert name to valid C identifier.
        
        Args:
            name: Original name
            
        Returns:
            Sanitized name suitable for C identifiers
        """
        # Replace dots, dashes, slashes with underscores
        sanitized = name.replace(".", "_").replace("-", "_").replace("/", "_")
        # Remove any non-alphanumeric characters
        sanitized = "".join(c for c in sanitized if c.isalnum() or c == "_")
        # Ensure it doesn't start with a digit
        if sanitized and sanitized[0].isdigit():
            sanitized = "_" + sanitized
        return sanitized.lower()
